<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.johannesbrodwall</groupId>
    <artifactId>contract-first-event-sourcing</artifactId>
    <version>latest</version>

    <dependencies>
        <dependency>
            <groupId>org.eclipse.jetty.ee10</groupId>
            <artifactId>jetty-ee10-webapp</artifactId>
            <version>12.1.0</version>
        </dependency>
        <dependency>
            <groupId>org.logevents</groupId>
            <artifactId>logevents</artifactId>
            <version>0.5.8</version>
        </dependency>

    </dependencies>
</project>