openapi: 3.0.3
info:
  title: Incident management
  description: Web socket API to share information about incidents
  version: 1.0.0
paths:
  /ws/messages:
    get:
      responses:
        200:
          description: Returns messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageFromServer"
components:
  schemas:
    MessageFromServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentSummaryList"
        - $ref: "#/components/schemas/IncidentSnapshot"
        - $ref: "#/components/schemas/IncidentEvent"

    MessageToServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentSummarySubscribeRequest"
        - $ref: "#/components/schemas/IncidentSubscribeRequest"
        - $ref: "#/components/schemas/IncidentCommand"
      discriminator:
        propertyName: type

    IncidentEvent:
      allOf:
        - $ref: "#/components/schemas/IncidentCommand"
        - properties:
            username:
              type: string
            sequenceId:
              type: integer
              format: int64
          required: [username, sequenceId]

    IncidentSummaryList:
      properties:
        summaries:
          type: array
          items:
            $ref: "#/components/schemas/IncidentSummary"
        lastSequenceId:
          type: integer
          format: int64
        replaceList:
          type: boolean
      required: [summaries, lastSequenceId]

    IncidentSummary:
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        info:
          $ref: "#/components/schemas/IncidentInfo"
      required: [id, info, createdAt, updatedAt]

    IncidentSnapshot:
      allOf:
        - $ref: "#/components/schemas/IncidentSummary"
        - properties:
            lastSequenceId:
              type: integer
              format: int64
            persons:
              additionalProperties:
                $ref: "#/components/schemas/InvolvedPersonInfo"
          required: [persons, lastSequenceId]

    IncidentInfo:
      properties:
        description:
          type: string
        priority:
          type: string
          enum: [ALERT, HIGH, MEDIUM, LOW]

    IncidentSummarySubscribeRequest:
      properties:
        lastSequenceId:
          type: integer
          format: int64

    IncidentSubscribeRequest:
      properties:
        incidentId:
          type: string
          format: uuid
      required: [incidentId]

    IncidentCommand:
      properties:
        clientTime:
          type: string
          format: date-time
        incidentId:
          type: string
          format: uuid
        delta:
          $ref: "#/components/schemas/IncidentDelta"
      required: [clientTime, incidentId, delta]

    IncidentDelta:
      oneOf:
        - $ref: "#/components/schemas/CreateIncidentDelta"
        - $ref: "#/components/schemas/UpdateIncidentDelta"
        - $ref: "#/components/schemas/AddPersonToIncidentDelta"
        - $ref: "#/components/schemas/UpdatePersonInIncidentDelta"
      discriminator:
        propertyName: delta

    CreateIncidentDelta:
      properties:
        info:
          $ref: "#/components/schemas/IncidentInfo"
      required: [info]

    UpdateIncidentDelta:
      properties:
        info:
          $ref: "#/components/schemas/IncidentInfo"
      required: [info]

    AddPersonToIncidentDelta:
      properties:
        personId:
          type: string
          format: uuid
        info:
          $ref: "#/components/schemas/InvolvedPersonInfo"
      required: [personId, info]

    UpdatePersonInIncidentDelta:
      properties:
        personId:
          type: string
          format: uuid
        info:
          $ref: "#/components/schemas/InvolvedPersonInfo"
      required: [personId, info]

    InvolvedPersonInfo:
      properties:
        firstName:
          type: string
        lastName:
          type: string
        role:
          type: string
          enum: [caller, suspect, witness]
