openapi: 3.1.0
info:
  title: Incident management
  description: Web socket API to share information about incidents
  version: 1.0.0
paths:
  /ws/messages:
    get:
      responses:
        200:
          description: Returns messages
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MessageFromServer"
components:
  schemas:
    MessageFromServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentSummaryList"

    MessageToServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentCommand"

    IncidentSummaryList:
      properties:
        summaries:
          type: array
          items:
            $ref: "#/components/schemas/IncidentSummary"
      required: [summaries]

    IncidentSummary:
      properties:
        id:
          type: string
          format: uuid
        description:
          type: string
      required: [id, description]

    IncidentCommand:
      properties:
        clientTime:
          type: string
          format: date-time
        incidentId:
          type: string
          format: uuid
        delta:
          $ref: "#/components/schemas/IncidentDelta"
      required: [clientTime, delta]

    IncidentDelta:
      oneOf:
        - $ref: "#/components/schemas/CreateIncidentDelta"

    CreateIncidentDelta:
      properties:
        description:
          type: string
