openapi: 3.0.3
info:
  title: Incident management
  version: 1.0.0
paths:
  /ws/incidents:
    get:
      responses:
        200:
          description: Web sockets incident event from server
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/MessageFromServer"
components:
  schemas:
    IncidentInfo:
      properties:
        summary:
          type: string
        priority:
          type: string
          enum: [HIGH, MEDIUM, LOW]

    MessageFromServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentSummaryList"
        - $ref: "#/components/schemas/IncidentSnapshot"
        - $ref: "#/components/schemas/IncidentEvent"

    MessageToServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentCommand"
        - $ref: "#/components/schemas/IncidentSubscribeRequest"
      discriminator:
        propertyName: type

    IncidentSummary:
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        info:
          $ref: "#/components/schemas/IncidentInfo"
      required: [id, createdAt, updatedAt, info]

    IncidentSnapshot:
      allOf:
        - $ref: "#/components/schemas/IncidentSummary"
        - properties:
            persons:
              additionalProperties:
                $ref: "#/components/schemas/PersonInfo"
          required: [persons]

    IncidentSummaryList:
      properties:
        incidents:
          type: array
          items:
            $ref: "#/components/schemas/IncidentSummary"
      required: [incidents]

    IncidentCommand:
      properties:
        eventId:
          type: string
          format: uuid
        incidentId:
          type: string
          format: uuid
        clientTime:
          type: string
          format: date-time
        delta:
          $ref: "#/components/schemas/IncidentDelta"
      required: [eventId, incidentId, clientTime, delta]

    IncidentEvent:
      allOf:
        - $ref: "#/components/schemas/IncidentCommand"
        - properties:
            serverTime:
              type: string
              format: date-time
          required: [serverTime]

    IncidentDelta:
      oneOf:
        - $ref: "#/components/schemas/CreateIncident"
        - $ref: "#/components/schemas/UpdateIncident"
        - $ref: "#/components/schemas/AddPersonToIncidentDelta"
      discriminator:
        propertyName: type

    CreateIncident:
      properties:
        info:
          $ref: "#/components/schemas/IncidentInfo"
      required: [info]

    UpdateIncident:
      properties:
        info:
          $ref: "#/components/schemas/IncidentInfo"
      required: [info]

    AddPersonToIncidentDelta:
      properties:
        personId:
          type: string
          format: uuid
        info:
          $ref: "#/components/schemas/PersonInfo"
      required: [personId, info]

    IncidentSubscribeRequest:
      properties:
        incidentId:
          type: string
          format: uuid
      required: [incidentId]

    PersonInfo:
      properties:
        givenName:
          type: string
        familyName:
          type: string
        role:
          enum: [CALLER, WITNESS, SUSPECT]
