openapi: 3.0.3
info:
  title: Incident management
  version: 1.0.0
paths:
  /api/incidents:
    get:
      responses:
        200:
          description: Returns the current incidents
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Incident"
  /ws/incidents:
    get:
      responses:
        200:
          description: Web sockets incident event from server
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MessageFromServer"
components:
  schemas:
    Incident:
      properties:
        summary:
          type: string
      required: [summary]

    MessageFromServer:
      oneOf:
        - $ref: "#/components/schemas/IncidentSummaryList"
        - $ref: "#/components/schemas/Incident"

    IncidentSummaryList:
      properties:
        incidents:
          type: array
          items:
            $ref: "#/components/schemas/Incident"
      required: [incidents]
